notifications:
  email: false

dist: bionic
language: node_js
node_js:
  - node

sudo: required

packages:
  - clang-8
  - libc++-8-dev
  - libc++abi-8-dev

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
  - docker exec -it emscripten make helloworld.js
  - docker exec -it emscripten emcc pace_calculator_js.cc -o pace.js --bind -O3 -std=c++17 -I"./external/pugixml-1.10/src" "./external/pugixml-1.10/src/pugixml.cpp"