notifications:
  email: false

dist: bionic
language: node_js
node_js:
  - node

sudo: required

packages:
  - clang-8
  - libc++-8-dev
  - libc++abi-8-dev

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
  - docker exec -it emscripten emcc ./src/pace_calculator_js.cc -o pace.js --bind -O3 -std=c++17 -I"./include" -I"./external/pugixml-1.10/src" "./external/pugixml-1.10/src/pugixml.cpp"

after_success:
  mkdir web
  cp ./pace.js ./web/gen/pace.js
  cp ./pace.wasm ./web/gen/pace.wasm


deploy:
  provider: pages
  skip_cleanup: true
  local_dir: web/  # or remove this line to upload from root of repo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

#deploy:
#  provider: releases
#  api_key: $GITHUB_OAUTH_TOKEN
#  file: release.zip
#  skip_cleanup: true
#  draft: true